### ISSUE TITLE
Github Gist not working

### ISSUE THREAD

**Issue by ibrahimduran** [tigerxy/VSCode-ShareCode#9]
Extension version: 0.4.0
Console log:
```
[Extension Host] read  authtoken : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[Extension Host] Uncaught Exception:  TypeError: Cannot read property 'html_url' of undefined
Cannot read property 'html_url' of undefined: TypeError: Cannot read property 'html_url' of undefined
    at client.gists.create (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\out\src\github.js:155:40)
    at global.sendError (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:795:13)
    at C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:802:29
    at callCallback (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:677:17)
    at IncomingMessage.<anonymous> (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:733:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Extension Host] TypeError: Cannot read property 'html_url' of undefined
    at client.gists.create (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\out\src\github.js:155:40)
    at global.sendError (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:795:13)
    at C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:802:29
    at callCallback (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:677:17)
    at IncomingMessage.<anonymous> (C:\Users\ibrah\.vscode\extensions\RolandGreim.sharecode-0.4.0\node_modules\github\lib\index.js:733:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by tigerxy** [comment]
Looks as if there is a mistake in the library. Which windows version and which version of visual studio code do you use?

**Comment by ibrahimduran** [comment]
VSCode: 1.9.0
OS: Windows 10 Version 16607 (Build 14393.693)

**Comment by ibrahimduran** [comment]
I still don't know the why this error occurred but looks like after some debugging and couple of reinstallations it's now working correctly.
